### ISSUE TITLE
MIME Types

### ISSUE THREAD

**Issue by Martin-Pitt** [sdogruyol/fast-http-server#10]
Really nice and super fast! But there are MIME type issues, for example a SVG will be served as `application/octet-stream` which breaks them from being rendered correctly.

Likewise missing MIME types for JPEG, PNG, GIF, WebP, albeit browser's content detection seems to work fine with these.

**Comment by Pyroglyph** [comment]
SVGs come through as `image/svg+xml` for me. I'm on Crystal 0.27.0 so it might have just been an old problem with a previous version of `HTTP::Server`?

**Comment by sdogruyol** [comment]
Yeah, this issue should be fixed in latest Crystal 0.27.0 :+1:
