### ISSUE TITLE
Crystal 0.11.1 support

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/fast-http-server#3]

**Comment by kbrock** [comment]
They did some work with paths and regular expressions.  wonder how much that has chaned the performance of this server :)

**Comment by sdogruyol** [comment]
@kbrock i'll update the benchmarks :+1:

**Comment by sdogruyol** [comment]
Seems like it improved the performance around %10 or so.

**Comment by kbrock** [comment]
@sdogruyol thanks
