### ISSUE TITLE
Performance number error?

### ISSUE THREAD

**Issue by brandonzylstra** [sdogruyol/fast-http-server#7]
It seems like there may be a mistake in the performance numbers:

> | Server | Request Per Second | Avg. Response Time |
> | :-- | :-: | --: |
> | fast-http-server (**_Crystal**_) | 18348.47 | 8.67ms |
> | http-server (**_Node.js**_) | 2105.55 | 47.92ms |
> | SimpleHTTPServer (**_Python**_) | 785.14 | 1.91ms |

According to these numbers, SimpleHTTPServer has a much _faster_ response than `fast-http-server`, even though `fast-http-server` can handle massively more requests per second.  Is this correct?  Is it possible that the units are off on one or the other?  (microseconds versus milliseconds)

**Comment by sdogruyol** [comment]
I've updated the README and this is no longer an issue https://github.com/sdogruyol/fast-http-server#fast
